export const FETCH_CHATS = "FETCH_CHATS";
export const FETCH_CHATS_DONE = "FETCH_CHATS_DONE";

export const FETCH_MESSAGES = "FETCH_MESSAGES";
export const FETCH_MESSAGES_DONE = "FETCH_MESSAGES_DONE";
export const CLOSE_CHAT = "CLOSE_CHAT";

export const TOGGLE_PANEL = "TOGGLE_PANEL";
export const TOGGLE_SEARCH = "TOGGLE_SEARCH";

export const ADD_NEW_MESSAGE = "ADD_NEW_MESSAGE";


export const LOGIN = "LOGIN";
export const LOGIN_DONE = "LOGIN_DONE";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REG = "REG";
export const REG_DONE = "REG_DONE";
export const REG_FAIL = "REG_FAIL";

export const CHANGE_PAGE = "CHANGE_PAGE";
export const REMOVE_STORE = "REMOVE_STORE";

export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_DONE = "FETCH_USER_DONE";
export const FETCH_USER_FAIL = "FETCH_USER_FAIL";

export const SEARCH = "SEARCH";
export const SEARCH_DONE = "SEARCH_DONE";
export const SEARCH_FAIL = "SEARCH_FAIL";

export const CREATE_CHAT = "CREATE_CHAT";
export const CREATE_CHAT_DONE = "CREATE_CHAT_DONE";
export const CREATE_CHAT_FAIL = "CREATE_CHAT_FAIL";

export const ADD_CHAT_TO_LIST = "ADD_CHAT_TO_LIST";

export const DELETE_MESSAGE = "DELETE_MESSAGE";
export const DELETE_MESSAGE_DONE = "DELETE_MESSAGE_DONE";

export const EDIT_MESSAGE = "EDIT_MESSAGE";
export const EDIT_MESSAGE_DONE = "EDIT_MESSAGE_DONE";

export const UPDATE_AVATAR = "UPDATE_AVATAR";
export const UPDATE_AVATAR_DONE = "UPDATE_AVATAR_DONE";

export const UPDATE_ABOUT = "UPDATE_ABOUT";
export const UPDATE_ABOUT_DONE = "UPDATE_ABOUT_DONE";

export const UPDATE_EMAIL = "UPDATE_EMAIL";
export const UPDATE_EMAIL_DONE = "UPDATE_EMAIL_DONE";

export const SEND_CONFIRM_MESSAGE = "SEND_CONFIRM_MESSAGE";

export const SEND_OPTIONS = "SEND_OPTIONS";
export const SEND_OPTIONS_DONE = "SEND_OPTIONS_DONE";