export const FETCH_CHATS = "FETCH_CHATS";
export const FETCH_CHATS_DONE = "FETCH_CHATS_DONE";

export const FETCH_MESSAGES = "FETCH_MESSAGES";
export const FETCH_MESSAGES_DONE = "FETCH_MESSAGES_DONE";

export const TOGGLE_PANEL = "TOGGLE_PANEL";